version: 0.2

env:
  variables:
    PULP_SERVER: "pulp"
    PULP_USER: "admin"
    PULP_CHANNEL: "extras"
  parameter-store:
    PULP_PASSWORD: "S3YumRepo-pulp-password"

phases:
  pre_build:
    commands:
      - apt-get update -y && apt-get install -y yum createrepo python-pip
      - pip install requests
      - echo Running sanity checks...
      - createrepo --version
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p repo && cd repo
      - ../pulp/query.py -s $PULP_SERVER -u $PULP_USER -p $PULP_PASSWORD -c $PULP_CHANNEL
      - createrepo -d .

artifacts:
  files:
    - 'repo/**/*'

cache:
  paths:
    - 'repo/*'
